apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-front-desk
spec:
  host: front-desk # interpreted as front-desk.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1 # label attached to Pod definition
  - name: v2
    labels:
      version: v2 # label attached to Pod definition
